name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # TOOL 1 - Secret Scanning (Gitleaks)
      - name: Secret Scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TOOL 2 - SAST with SpotBugs
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SAST with SpotBugs
        run: mvn spotbugs:check || true

      # TOOL 3 - SCA with OWASP Dependency Check
      - name: Run SCA with OWASP Dependency Check
        run: mvn dependency-check:check || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: target/